download_yale_event_log:
  name: "service.download_yale_event_log.name"
  description: "service.download_yale_event_log.description"
  fields:
    pages:
      description: "service.download_yale_event_log.fields.pages.description"
      required: false
      example: "2"
      selector:
        text:
  response:
    description: "service.download_yale_event_log.response.description"
    fields:
      event_log_table:
        description: "service.download_yale_event_log.response.fields.event_log_table.description"
        selector:
          object:
      total_rows_returned:
        description: "service.download_yale_event_log.response.fields.total_rows_returned.description"
        selector:
          object:
      pages_fetched:
        description: "service.download_yale_event_log.response.fields.pages_fetched.description"
        selector:
          number: